title: Pierre Fenoll's thoughts
description: Posts on current / past / future projects and ideas on the crazy spectrum
baseurl: ''
url: https://fenollp.github.io/
future: true
highlighter: rouge

asciidoctor:
  attributes:
  - idprefix=_
  - source-highlighter=rouge

plugins:
- jekyll-paginate
# - jekyll-asciidoc
# - jekyll-time-to-read
# - jekyll-redirect-from

excerpt_separator: ''
pygments: true
markdown: kramdown
paginate: 5
show_downloads: true
