excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://fenollp.github.io
title: Pierre Fenoll
paginate: 5
description: 
google_analytics: 
show_downloads: true
theme: jekyll-theme-hacker