# syntax=docker.io/docker/dockerfile:1@sha256:db1ff77fb637a5955317c7a3a62540196396d565f3dd5742e76dddbb6d75c4c5
# docker build -f Dockerfile.wahaj_generator -t final -o . . && open wahaj_generator.stl

FROM python:3 AS builder

# Install dependencies
RUN pip install numpy numpy-stl

WORKDIR /app

COPY /wahaj_generator.py .

RUN python3 wahaj_generator.py

FROM scratch AS final
COPY --from=builder /app/wahaj_generator.stl /wahaj_generator.stl
