name: CI

on:
  push:
  pull_request:

jobs:

  ci:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Find missing assets
      run: |
        pwd
        ls -lha .
        set -o pipefail
        grep -Eo 'assets/[^")]+' -r . | \
          grep -v .github/workflows/ci.yml | \
          cut -d: -f2 | \
          sort -u | \
          grep -v assets/css/layout.css | \
          while read -r p; do echo "$p"; if ! [[ -r "$p" ]]; then exit 1; fi; done
